/* AUTO GENERATED BY make. DO NOT EDIT! */

#define RELEASE ""
#define BLAME "LibXenon.org"
#define DATE "2021-04-01"
#define GITREV "2eef72b"

#define VERSION RELEASE "-git-" GITREV
#define LONGVERSION VERSION " " DATE " (" BLAME ")"
#define GCC_VERSION "4.7.1"
#define BINUTILS_VERSION "2.22"
